### ISSUE TITLE
Counter not increasing

### ISSUE THREAD

**Issue by ghost974** [dschneller/haproxy-http-based-rate-limiting#1]
Hello,

I'm trying to implement a similar kind of throttling and I'm not having the expected result :
I have lowered the threshold to something very low, 5 reqs in 10 sec.

 In my frontend : 

```
tcp-request inspect-delay 5s
acl is_sys path_beg -i /sys
acl too_many_req sc0_gpc0_rate() gt 5
acl mark_seen sc0_inc_gpc0 gt 0
stick-table type string size 100k store gpc0_rate(10s)
tcp-request content track-sc0 hdr(Authorization) if METH_GET is_sys
use_backend slow_down if too_many_req mark_seen
[...]

backend slow_down
  mode http
  timeout tarpit 2s
  http-request tarpit
```

I start sending some concurrent requests (20 concurrent, average of 50req/s) and do a show table :

```
0xe3663c: key=Basic\ xxxxxxxxxxxxxx use=0 exp=0 gpc0_rate(10000)=0
```

It stays like that and do not increase. It seems like the mark_seen acl is not kicking in or something, any idea ?

Thanks

**Comment by dschneller** [comment]
Simple issue, hard to find. Had to try it out first, to be sure.
ACLs are executed with logical `AND` and apparently haproxy uses short-circuit evaluation (https://en.wikipedia.org/wiki/Short-circuit_evaluation).

That means, multiple ACLs are evaluated from left to right. Once the first one is `false`, there is no point in evaluating the remaining ones, because the overall expression cannot become `true` again.

In your example you have

```
use backend_slow if too_many_req (AND) mark_seen
```

Because `too_many_req` will initially always be false, `mark_seen` never gets executed. You need to make sure, the requests actually get counted. Swap the two, and you are in business:

```
use backend_slow if mark_seen too_many_req
```

From my test just now:

```
> show table fe_plain
# table: fe_plain, type: string, size:102400, used:1
0x1d200cc: key=A use=1 exp=0 gpc0_rate(10000)=5
```

**Comment by dschneller** [comment]
I first did not understand this, because on our prod system the order was actually correct. Nasty little issue. Blogpost was amended with a new paragraph about this, too. Thanks for noticing.

**Comment by ghost974** [comment]
Thank you !! I would have never found it.
